defmodule TamilCharacters do
  use Constants

  constant(ka, "\u0b95")
  constant(nga, "\u0b99")
  constant(sa, "\u0b9a")
  constant(nja, "\u0b9e")
  constant(da, "\u0b9f")
  constant(nnna, "\u0ba3")
  constant(ta, "\u0ba4")
  constant(nna, "\u0ba8")
  constant(na, "\u0ba9")
  constant(pa, "\u0baa")
  constant(ma, "\u0bae")
  constant(ya, "\u0baf")
  constant(ra, "\u0bb0")
  constant(rra, "\u0bb1")
  constant(la, "\u0bb2")
  constant(lla, "\u0bb3")
  constant(za, "\u0bb4")
  constant(va, "\u0bb5")

  constant(v_a, "\u0b85")
  constant(v_aa, "\u0b86")
  constant(v_i, "\u0b87")
  constant(v_ii, "u\0b88")
  constant(v_u, "\u0b89")
  constant(v_uu, "\u0b8a")
  constant(v_e, "u\0b8e")
  constant(v_ee, "\u0b8f")
  constant(v_ai, "\u0b90")
  constant(v_o, "\u0b92")
  constant(v_oo, "\u0b93")
  constant(v_au, "\u0b94")

  constant(pulli, "\u0bcd")
  constant(thunaikaal, "\u0bbe")
  constant(i, "\u0bbf")
  constant(ii, "\u0bc0")
  constant(u, "\u0bc1")
  constant(uu, "\u0bc2")
  constant(e, "\u0bc6")
  constant(ee, "\u0bc7")
  constant(ai, "\u0bc8")
  constant(o1, "\u0bc6\u0bbe")
  constant(o, "\u0bca")
  constant(oo1, "\u0bc7\u0bbe")
  constant(oo, "\u0bcb")
  constant(au1, "\u0bc6\u0bd7")
  constant(au, "\u0bcc")
end
